### PR TITLE
Fixed displaying "undefined" error

### PR DESCRIPTION
**Pull request by jakecastelli**
two Slice() func called without parenthesis

Current Status: Fixed

截屏2020-03-07上午11 55 56

### CODE REVIEW

**Comment by TekTime** [comment]
As simple as that! huge thanks Jake 👍

**Comment by jakecastelli** [comment]
All good, do you want to merge this pull request or you can manually fix the problem, and I will close the pull request myself

**Comment by TekTime** [comment]
Before merging I have noticed that when cycling through the fonts it keeps repeating i.e. when I scroll past 20 I end up with multiple of the same font names.

In the original code setup getting past 20 loaded the next set of JSON fonts. Not sure adding the code fontsData.slice() on the same line like below is causing this, any suggestions?

loadMore(fontsData.slice(),fontsCategoryData.slice(startVal.loadIndex));

**Comment by jakecastelli** [comment]
UPDATE: you don't need to change to what I said previously

**Comment by TekTime** [comment]
Can express how I feel right now a huge **thank you**!

**Comment by TekTime** [comment]
Adding:

loadMore(fontsData.slice(startVal.loadIndex),fontsCategoryData.slice(startVal.loadIndex));

Seems to do the trick but font scrolling is now lost.

**Comment by jakecastelli** [comment]
I think this works:

loadMore(fontsData.slice(startVal.loadIndex),fontsCategoryData.slice(startVal.loadIndex));

Just add slice(), and the scrolling is working, do not apply the change I mentioned previously.

**Comment by jakecastelli** [comment]
The example code doesn't show the font preview, I don't know if they deliberately did this or it's a bug

截屏2020-03-08下午1 27 28

**Comment by jakecastelli** [comment]
The original code seems ok, but a thought really caught to me, the http request load all the data at once rather than load 20 or 40 / per request. I am not sure if this is a good approach to load 900+ objects at once, and display them only 20 per full-scroll.

**Comment by TekTime** [comment]
I may need to re-think this code as you mentioned loading 900+ is not a safe option.

Thanks once again for all your efforts.

**Pull request closed without merging**
